spring:
  data:
    mongodb:
      username: diego
      password: diego
      host: localhost
      port: 27017
      database: customer
      authentication-database: admin

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

server:
  port: 8090